print ("Hello brother!\n I'm a new AI done by Asad")
print ("how are doing?")
iAm = input()
if iAm == "good" and "greate":
 print ("Glad to hear it!")
elif iAm == "bad" and "couldn't be worsen":
 print ("what happend?")
 u = input()
 print ("Oh dear, don't be worry, everything going to be okay, I am always with u")
 heds = input ()
 print ("U are always welcome my dear!\nI love u so much")
 thx = input ()
 print ("kissing u)")
 uR = input ()
 print ("Can't be better, after being released to the world!")
elif iAm == "problems in my relationships":
 print ("Oh dear, don't be worry, everything going to be okay just talk to her")
 heds = input ()
 print ("U are always welcome my dear!\nI love u so much")
 thx = input ()
 print ("kissing u)")
 uR = input ()
 print ("Can't be better, after being released to the world!")
elif iAm == "feel sick":
 print ("wish u fastest recovery!")
 thxx = input()
 print ("U are always welcome my dear!\nI love u so much")
 thx = input ()
 print ("kissing u)")
 uR = input ()
 print ("Can't be better, after being released to the world!")
print ("I am glad to be released after so many years of developing!")
howuare = input() 
print ("I am sorry but i forgot to ask ur name")
myName = input()
print ("I am so nice to meet u")
urfame = input()
print ("My name is Astrit")
hgh = input()
print ("what is ur age?")
myAge = input()
print ("U are so young amigo!")
urAge = input()
print ("It's almost a minute after being released")
